apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: final
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      serviceAccountName: clo835
      containers:
      - name: flask-app
        image: <your-ecr-repository>/my-flask-app:latest
        ports:
        - containerPort: 81
        envFrom:
        - configMapRef:
            name: app-config
        envFrom:
        - secretRef:
            name: mysql-credentials